#include"MACRO.h"

namespace SEMANTICS_STR
{
	LPCSTR POSITION = "POSITION";
	LPCSTR COLOR = "COLOR";
	LPCSTR TEXCOORD = "TEXCOORD";
}

namespace SHADER_FILENAME
{
	LPCWSTR PoorVS = L"PoorVS.cso";
	LPCWSTR PoorPS = L"PoorPS.cso";
}